dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  # CLONE AND BUILD GTEST
  - cd unit_tests
  - git clone https://github.com/google/googletest.git
  - cd ../
  # BUILD ZZ_SYNTH
  - mkdir build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Release ../
  - make
  # RUN UNIT TESTS
  - ./unit_tests/UnitSynth
