language: cpp
compiler:
  - clang
  - gcc
script:
  # CLONE AND BUILD GTEST
  - cd unit_tests
  - git clone https://github.com/google/googletest.git
  - cd googletest/googletest/make
  - make gtest.a
  - cd ../../../../
  # BUILD ZZ_SYNTH
  - mkdir bin
  - mkdir lib
  - mv /home/travis/build/zimzum/zz_synth//unit_tests/googletest/googletest/make/gtest.a /home/travis/build/zimzum/zz_synth//unit_tests/googletest/googletest/make/libgtest.a
  - make ZZDIR=$PWD/ all_recursive
  # RUN UNIT TESTS
  - ./bin/testbench_envelope.out
  - ./bin/testbench_segment.out
  - ./bin/testbench_rww.out
